# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  Install_dependencies:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-packages:
          app-dir: /server 
      

workflows:
  example-workflow:
    jobs:
      - Install_dependencies
      