version: 2.1
orbs:
  node: circleci/node@4.7.0
  codecov: codecov/codecov@1.0.2

jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - codecov/upload:
          file: './coverage/clover.xml'
          token: 67989bd3-0146-4b00-ab2f-687f58fb1700
     

  deploy: # this can be any name you choose
    docker:
      - image: cimg/node:17.2.0
    steps:
      - attach_workspace:
          at: ~/project

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main